g++ \
	-O1 \
	-Wall \
	-shared \
	-std=c++11 \
	-fPIC \
	-I/usr/include/python3.8 \
	-I/usr/local/lib/python3.8/dist-packages/pybind11/include \
	-I. \
    ./pybind11.cc \
    ./sdk.cc \
    ./common/file.cc \
    ./common/filepath.cc \
    ./crane/client.cc \
    ./crane/crane.pb.cc \
    ./crane/crane.grpc.pb.cc \
    ./uri/uri.cc \
	-o mldb.cpython-38-x86_64-linux-gnu.so \
	-L/usr/local/lib \
	-L/usr/local/lib \
	-lprotobuf \
	-lpthread \
	-lgrpc++ \
	-labsl_bad_optional_access \
	-labsl_str_format_internal \
	-labsl_time \
	-labsl_time_zone \
	-labsl_civil_time \
	-labsl_strings \
	-labsl_strings_internal \
	-labsl_throw_delegate \
	-labsl_int128 \
	-labsl_base \
	-labsl_spinlock_wait \
	-labsl_raw_logging_internal \
	-labsl_log_severity \
	-labsl_dynamic_annotations \
	-lgrpc \
	-laddress_sorting \
	-lre2 \
	-lupb \
	-lcares \
	-lz \
	-labsl_bad_optional_access \
	-labsl_str_format_internal \
	-labsl_time \
	-labsl_time_zone \
	-labsl_civil_time \
	-labsl_strings \
	-labsl_strings_internal \
	-labsl_throw_delegate \
	-labsl_int128 \
	-labsl_base \
	-labsl_spinlock_wait \
	-labsl_raw_logging_internal \
	-labsl_log_severity \
	-labsl_dynamic_annotations \
	-lgpr \
	-labsl_str_format_internal \
	-labsl_time \
	-labsl_time_zone \
	-labsl_civil_time \
	-labsl_strings \
	-labsl_strings_internal \
	-labsl_throw_delegate \
	-labsl_int128 \
	-labsl_base \
	-labsl_spinlock_wait \
	-labsl_raw_logging_internal \
	-labsl_log_severity \
	-labsl_dynamic_annotations \
	-lssl \
	-lcrypto \
	-pthread \
	-Wl,--no-as-needed \
	-lgrpc++_reflection \
	-Wl,--as-needed \
	-ldl