g++ \
    -pthread \
    -shared \
    -Wl,-O1 \
    -Wl,-z,relro \
    -g \
    -fwrapv \
    -O2 \
    -Wl,-z,relro \
    -g \
    -fwrapv \
    -O2 \
    -g \
    -fstack-protector-strong \
    -Wformat \
    -Werror=format-security \
    -Wdate-time \
    -D_FORTIFY_SOURCE=2 \
    ./pybind11.cc \
    ./sdk.cc \
    ./common/file.cc \
    ./common/filepath.cc \
    ./crane/client.cc \
    ./crane/crane.pb.cc \
    ./crane/crane.grpc.pb.cc \
    ./uri/uri.cc \
    -L/usr/local/lib \
    -lprotobuf \
    -lpthread \
    -lgrpc++ \
    -labsl_bad_optional_access \
    -labsl_str_format_internal \
    -labsl_time \
    -labsl_time_zone \
    -labsl_civil_time \
    -labsl_strings \
    -labsl_strings_internal \
    -labsl_throw_delegate \
    -labsl_int128 \
    -labsl_base \
    -labsl_spinlock_wait \
    -labsl_raw_logging_internal \
    -labsl_log_severity \
    -labsl_dynamic_annotations \
    -lgrpc \
    -laddress_sorting \
    -lupb \
    -lcares \
    -lz \
    -labsl_bad_optional_access \
    -labsl_str_format_internal \
    -labsl_time \
    -labsl_time_zone \
    -labsl_civil_time \
    -labsl_strings \
    -labsl_strings_internal \
    -labsl_throw_delegate \
    -labsl_int128 \
    -labsl_base \
    -labsl_spinlock_wait \
    -labsl_raw_logging_internal \
    -labsl_log_severity \
    -labsl_dynamic_annotations \
    -lgpr \
    -labsl_str_format_internal \
    -labsl_time \
    -labsl_time_zone \
    -labsl_civil_time \
    -labsl_strings \
    -labsl_strings_internal \
    -labsl_throw_delegate \
    -labsl_int128 \
    -labsl_base \
    -labsl_spinlock_wait \
    -labsl_raw_logging_internal \
    -labsl_log_severity \
    -labsl_dynamic_annotations \
    -lssl -lcrypto \
    -ldl \
    -lgrpc++_reflection \
    -o mldb.cpython-38-x86_64-linux-gnu.so \
    -I. \
    -I/usr/include/python3.8 \
    -fPIC